"""Reporting Execution Agent — writes the Markdown report to disk."""

from __future__ import annotations

from analyst.base_agent import BaseAgent
from analyst.models import Severity, AgentResult
from analyst.registry import register_agent
from analyst.state import AnalysisState


@register_agent("reporting_execution")
class ReportingExecutionAgent(BaseAgent):
    """Saves the final analysis report generated by the Insight Report Reasoner."""

    name = "reporting_execution"
    description = "Execution: Save Report"

    def run(self, state: AnalysisState) -> tuple[AnalysisState, AgentResult]:
        output_dir = state.output_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        report_content = "No intelligence generated. Proceeding to finalize."
        if state.eda_results and "final_markdown_report" in state.eda_results:
            report_content = state.eda_results["final_markdown_report"]

        report_path = output_dir / "report.md"
        report_path.write_text(report_content)
        state.report_path = report_path

        state.log(self.name, f"Report written to {report_path}", Severity.INFO)
        return state, AgentResult(
            agent_name=self.name,
            status="success",
            reasoning=f"Generated report at {report_path}",
            data_summary={"report_path": str(report_path)}
        )
